-- No foreign keys in the run store (D60). The code keeps the links instead:
-- every write checks that its run (and submission) exists, and deleteRun
-- deletes the run's rows from every table itself. The rule is in
-- migrations/AGENTS.md.
--
-- This drops every foreign key constraint in schema triage: the ones 0001
-- created on submissions, evidence, reports and feedback, and the one each
-- per-model embedding table (triage.emb_<slug>) got when the provider created
-- it, and any other there is (an unmerged draft of 0004 had one on
-- run_usage). Their names were generated by Postgres and the embedding tables
-- differ per install, so the constraints are found in pg_constraint, not
-- named here.
--
-- No index goes with them: Postgres never creates one for a foreign key.
-- Every table that held one keeps an index that starts with run_id (its
-- primary key, or feedback_run_id_idx on feedback), and reports keeps its
-- (run_id, seq) primary key, so no index is added.
--
-- Every server and CLI process must restart on code from D60 on once this has
-- applied. A process still on older code creates new emb_* tables with a
-- foreign key and relies on cascades in deleteRun; this file does not run
-- again to drop what it adds.

DO $$
DECLARE
  fk record;
BEGIN
  FOR fk IN
    SELECT t.relname AS table_name, c.conname AS constraint_name
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    WHERE c.contype = 'f' AND c.connamespace = 'triage'::regnamespace
    ORDER BY t.relname, c.conname
  LOOP
    EXECUTE format('ALTER TABLE triage.%I DROP CONSTRAINT %I', fk.table_name, fk.constraint_name);
  END LOOP;
END
$$;
