import { afterEach, describe, expect, test } from 'bun:test';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { GenIndexError, INDEX_SPECS, generate, main } from './gen-indexes.ts';

const roots: string[] = [];

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'gen-indexes-'));
  roots.push(root);
  return root;
}

function put(root: string, rel: string, text: string): void {
  const abs = join(root, rel);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, text);
}

async function load(root: string, rel: string): Promise<Record<string, unknown>> {
  // A query string defeats the module cache between runs of the same path.
  const url = `${pathToFileURL(join(root, rel)).href}?t=${Date.now()}-${Math.random()}`;
  return (await import(url)) as Record<string, unknown>;
}

const read = (root: string, rel: string): string => readFileSync(join(root, rel), 'utf8');

// Keep main() quiet in test output.
const quiet = <T>(fn: () => T): T => {
  const original = console.error;
  console.error = () => {};
  try {
    return fn();
  } finally {
    console.error = original;
  }
};

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe('gen-indexes', () => {
  test('empty tree writes four files, each exporting an empty frozen array', async () => {
    const root = makeRoot();
    const { stale } = generate({ root });
    expect(stale.sort()).toEqual([
      'src/agents/agent-modules.gen.ts',
      'src/cli/command-modules.gen.ts',
      'src/http/http-modules.gen.ts',
      'src/tools/tool-modules.gen.ts',
    ]);
    for (const spec of INDEX_SPECS) {
      const text = read(root, spec.out);
      expect(text).toContain(`export const ${spec.listName} = Object.freeze([]);`);
      expect(text).not.toMatch(/\bimport\b|\btype\b/);
      const mod = await load(root, spec.out);
      expect(mod[spec.listName]).toEqual([]);
      expect(Object.isFrozen(mod[spec.listName])).toBe(true);
    }
  });

  test('two tools in nested dirs are listed sorted by posix path, and output is stable', async () => {
    const root = makeRoot();
    put(root, 'src/tools/zeta.tool.ts', "export const toolModule = { name: 'zeta' };\n");
    put(root, 'src/tools/code/beta.tool.ts', "export const toolModule = { name: 'beta' };\n");
    put(root, 'src/tools/code/beta.tool.test.ts', 'this is a test file and must be ignored\n');
    put(root, 'src/tools/a/alpha.tool.ts', "export const toolModule = { name: 'alpha' };\n");

    generate({ root });
    const first = read(root, 'src/tools/tool-modules.gen.ts');
    expect(first).toBe(
      [
        '// Generated by scripts/gen-indexes.ts from src/tools/**/*.tool.ts. Do not edit.',
        "import { toolModule as m0 } from './a/alpha.tool.ts';",
        "import { toolModule as m1 } from './code/beta.tool.ts';",
        "import { toolModule as m2 } from './zeta.tool.ts';",
        '',
        'export const toolModules = Object.freeze([m0, m1, m2]);',
        '',
      ].join('\n'),
    );

    expect(generate({ root }).stale).toEqual([]);
    expect(read(root, 'src/tools/tool-modules.gen.ts')).toBe(first);

    const mod = await load(root, 'src/tools/tool-modules.gen.ts');
    expect((mod.toolModules as { name: string }[]).map((m) => m.name)).toEqual(['alpha', 'beta', 'zeta']);
  });

  test('agents are scanned one level deep; commands and http modules recursively', () => {
    const root = makeRoot();
    put(root, 'src/agents/triage.agent.ts', "'use agent';\nexport const rootAgent = 1;\n");
    put(root, 'src/agents/delegates/inner.agent.ts', 'no export here\n');
    put(root, 'src/cli/commands/tunnel/up.command.ts', 'export const command = 1;\n');
    put(root, 'src/http/auth/bearer.http.ts', 'export const httpModule = 1;\n');

    generate({ root });
    expect(read(root, 'src/agents/agent-modules.gen.ts')).toContain(
      "import { rootAgent as m0 } from './triage.agent.ts';",
    );
    expect(read(root, 'src/agents/agent-modules.gen.ts')).not.toContain('delegates');
    expect(read(root, 'src/cli/command-modules.gen.ts')).toContain(
      "import { command as m0 } from './commands/tunnel/up.command.ts';",
    );
    expect(read(root, 'src/http/http-modules.gen.ts')).toContain(
      "import { httpModule as m0 } from './auth/bearer.http.ts';",
    );
  });

  test('a tool file without export const toolModule fails and names the file', () => {
    const root = makeRoot();
    put(root, 'src/tools/good.tool.ts', 'export const toolModule = 1;\n');
    put(root, 'src/tools/ssfb/broken.tool.ts', 'export const toolModuleX = 1;\nexport function toolModule() {}\n');

    expect(() => generate({ root })).toThrow(GenIndexError);
    expect(() => generate({ root })).toThrow("src/tools/ssfb/broken.tool.ts: missing 'export const toolModule'");
    expect(quiet(() => main([], root))).toBe(1);
    expect(existsSync(join(root, 'src/tools/tool-modules.gen.ts'))).toBe(false);
  });

  test('--check exits 0 when fresh, 1 when a module was added, and writes nothing', () => {
    const root = makeRoot();
    expect(quiet(() => main(['--check'], root))).toBe(1); // nothing generated yet
    expect(main([], root)).toBe(0);
    expect(main(['--check'], root)).toBe(0);

    put(root, 'src/tools/new.tool.ts', 'export const toolModule = 1;\n');
    const before = read(root, 'src/tools/tool-modules.gen.ts');
    expect(quiet(() => main(['--check'], root))).toBe(1);
    expect(read(root, 'src/tools/tool-modules.gen.ts')).toBe(before);

    expect(main([], root)).toBe(0);
    expect(main(['--check'], root)).toBe(0);
  });

  test('--check also fails on a module without its export', () => {
    const root = makeRoot();
    main([], root);
    put(root, 'src/http/x.http.ts', 'export default 1;\n');
    expect(quiet(() => main(['--check'], root))).toBe(1);
  });
});
