// Writes the gitignored import lists that let areas register tools, agents,
// CLI commands and HTTP modules by adding a file, without editing a shared
// index. Run with `bun run gen`; `--check` only reports stale lists.
//
// Output is sorted by posix path and contains no type imports, so it is
// byte-identical across runs and compiles before any shared types exist.
// Only node:fs and node:path are used, so this also runs under Node.

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

export type IndexSpec = {
  /** Directory scanned, relative to the repo root. */
  dir: string;
  /** Scan subdirectories too. */
  recursive: boolean;
  /** File name suffix that marks a module. */
  suffix: string;
  /** Named export every matched file must declare with `export const`. */
  exportName: string;
  /** Output file, relative to the repo root. */
  out: string;
  /** Name of the array the output file exports. */
  listName: string;
};

export const INDEX_SPECS: readonly IndexSpec[] = [
  { dir: 'src/tools', recursive: true, suffix: '.tool.ts', exportName: 'toolModule', out: 'src/tools/tool-modules.gen.ts', listName: 'toolModules' },
  { dir: 'src/agents', recursive: false, suffix: '.agent.ts', exportName: 'rootAgent', out: 'src/agents/agent-modules.gen.ts', listName: 'rootAgents' },
  { dir: 'src/cli/commands', recursive: true, suffix: '.command.ts', exportName: 'command', out: 'src/cli/command-modules.gen.ts', listName: 'commands' },
  { dir: 'src/http', recursive: true, suffix: '.http.ts', exportName: 'httpModule', out: 'src/http/http-modules.gen.ts', listName: 'httpModules' },
];

export class GenIndexError extends Error {
  override name = 'GenIndexError';
}

const toPosix = (p: string): string => p.split(sep).join('/');

/** Plain code-unit comparison, so order does not depend on locale. */
const byPath = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

function listFiles(absDir: string, recursive: boolean): string[] {
  if (!existsSync(absDir)) return [];
  const found: string[] = [];
  for (const entry of readdirSync(absDir, { withFileTypes: true })) {
    const abs = join(absDir, entry.name);
    if (entry.isDirectory()) {
      if (recursive && entry.name !== 'node_modules') found.push(...listFiles(abs, true));
    } else if (entry.isFile()) {
      found.push(abs);
    }
  }
  return found;
}

function hasExport(source: string, name: string): boolean {
  return new RegExp(`^\\s*export\\s+const\\s+${name}\\b`, 'm').test(source);
}

/** Matched module paths for one spec, relative to the root, posix, sorted. */
export function findModules(root: string, spec: IndexSpec): string[] {
  return listFiles(join(root, spec.dir), spec.recursive)
    .map((abs) => toPosix(relative(root, abs)))
    .filter((rel) => rel.endsWith(spec.suffix))
    .sort(byPath);
}

/** Renders one output file. Throws GenIndexError naming a file without the export. */
export function renderIndex(root: string, spec: IndexSpec): string {
  const modules = findModules(root, spec);
  const outDir = dirname(spec.out);
  const lines = [
    `// Generated by scripts/gen-indexes.ts from ${spec.dir}/${spec.recursive ? '**/' : ''}*${spec.suffix}. Do not edit.`,
  ];
  modules.forEach((rel, i) => {
    const source = readFileSync(join(root, rel), 'utf8');
    if (!hasExport(source, spec.exportName)) {
      throw new GenIndexError(`${rel}: missing 'export const ${spec.exportName}'`);
    }
    let importPath = toPosix(relative(outDir, rel));
    if (!importPath.startsWith('.')) importPath = `./${importPath}`;
    lines.push(`import { ${spec.exportName} as m${i} } from '${importPath}';`);
  });
  const items = modules.map((_, i) => `m${i}`).join(', ');
  lines.push('', `export const ${spec.listName} = Object.freeze([${items}]);`, '');
  return lines.join('\n');
}

export type GenResult = {
  /** Output files (relative to root) whose content changed or would change. */
  stale: string[];
};

/**
 * Renders every index. With check=false it writes the stale ones; with
 * check=true it writes nothing and only reports them.
 */
export function generate(options: { root: string; check?: boolean }): GenResult {
  const root = resolve(options.root);
  const rendered = INDEX_SPECS.map((spec) => ({ spec, text: renderIndex(root, spec) }));
  const stale: string[] = [];
  for (const { spec, text } of rendered) {
    const abs = join(root, spec.out);
    const current = existsSync(abs) ? readFileSync(abs, 'utf8') : undefined;
    if (current === text) continue;
    stale.push(spec.out);
    if (!options.check) {
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, text);
    }
  }
  return { stale };
}

export const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** CLI entry. Returns the exit code: 0 ok, 1 stale (with --check) or a module without its export. */
export function main(argv: readonly string[], root: string = REPO_ROOT): number {
  const check = argv.includes('--check');
  try {
    const { stale } = generate({ root, check });
    if (check && stale.length > 0) {
      console.error(`gen --check: stale, run bun run gen: ${stale.join(', ')}`);
      return 1;
    }
    return 0;
  } catch (err) {
    if (err instanceof GenIndexError) {
      console.error(`gen: ${err.message}`);
      return 1;
    }
    throw err;
  }
}

if (import.meta.main) process.exit(main(process.argv.slice(2)));
