// Root agents from the generated agent list, checked for unique identities.
// Do not edit this file to add an agent: add src/agents/<name>.agent.ts
// exporting `rootAgent` instead (CONVENTIONS.md).

import type { Agent } from '@flue/runtime';
import { rootAgents as generated } from './agent-modules.gen.ts';

export class DuplicateAgentNameError extends Error {
  override readonly name = 'DuplicateAgentNameError';
}

export class AgentIndexError extends Error {
  override readonly name = 'AgentIndexError';
}

/** Flue's durable identity for a root agent: the agentName static, else the function name. */
export function agentNameOf(agent: Agent): string {
  const explicit = (agent as { agentName?: unknown }).agentName;
  return typeof explicit === 'string' && explicit !== '' ? explicit : agent.name;
}

/** Returns the list frozen, or throws when an agent has no identity or two share one. */
export function checkRootAgents(agents: readonly Agent[]): readonly Agent[] {
  const seen = new Map<string, number>();
  agents.forEach((agent, index) => {
    if (typeof agent !== 'function') throw new AgentIndexError(`root agent #${index} is not a function`);
    const name = agentNameOf(agent);
    if (name === '') throw new AgentIndexError(`root agent #${index} has no agentName and no function name`);
    const other = seen.get(name);
    if (other !== undefined) {
      throw new DuplicateAgentNameError(`duplicate agentName '${name}': root agents #${other} and #${index}`);
    }
    seen.set(name, index);
  });
  return Object.freeze([...agents]);
}

export const rootAgents: readonly Agent[] = checkRootAgents(generated as readonly unknown[] as readonly Agent[]);
