// Builds tool sets from the generated tool list. The agents call
// toolsFor(mount, ctx); the tripwire uses allToolNames(); doctor uses
// mountPlan(mount, ctx). Do not edit this file to register a tool: add a
// *.tool.ts file instead (CONVENTIONS.md).

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ToolDefinition } from '@flue/runtime/tool';
import { ENTITIES, type Entity } from '../types/core.ts';
import { toolModules } from './tool-modules.gen.ts';
import { MOUNTS, type Mount, type ToolContext, type ToolModule } from './types.ts';

/** Names Flue owns: framework tools and the six sandbox tools. */
export const RESERVED_TOOL_NAMES: readonly string[] = Object.freeze([
  'task',
  'activate_skill',
  'read_skill_resource',
  'finish',
  'give_up',
  'read',
  'write',
  'edit',
  'bash',
  'grep',
  'glob',
]);

export const TOOL_NAME_PATTERN = /^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$/;

/** Input keys a tool must never expose: entity and run id come from the closure (D3). */
export const FORBIDDEN_INPUT_KEYS: readonly string[] = Object.freeze(['entity', 'run_id', 'runId']);

const OBJECT_SCHEMA_TYPES = new Set(['object', 'strict_object', 'loose_object']);

export class ToolIndexError extends Error {
  override readonly name: string = 'ToolIndexError';
}
export class DuplicateToolNameError extends ToolIndexError {
  override readonly name = 'DuplicateToolNameError';
}
export class ReservedToolNameError extends ToolIndexError {
  override readonly name = 'ReservedToolNameError';
}
export class ToolNameMismatchError extends ToolIndexError {
  override readonly name = 'ToolNameMismatchError';
}

export type MountPlanRow =
  | { readonly name: string; readonly on: true }
  | { readonly name: string; readonly on: false; readonly reason: string };

export type ToolIndex = {
  readonly modules: readonly ToolModule[];
  /** Every module name, sorted and unique. */
  allToolNames(): readonly string[];
  /** Enabled tools for the mount, after entity filtering and name checks. Calls create() only for enabled modules. */
  toolsFor(mount: Mount, ctx: ToolContext): ToolDefinition[];
  /** Every module the mount would consider for this context, with on/off and the off reason. Never calls create(). */
  mountPlan(mount: Mount, ctx: ToolContext): readonly MountPlanRow[];
};

export type ToolIndexOptions = {
  /** Source file of each module, same order as the list. Used only in error messages. */
  readonly sources?: readonly string[] | (() => readonly string[]);
};

export function buildToolIndex(modules: readonly ToolModule[], options: ToolIndexOptions = {}): ToolIndex {
  const sourceOf = sourceNamer(modules, options.sources);
  modules.forEach((m, i) => checkModuleShape(m, sourceOf(i)));

  // Modules for the mount, with their list index for error messages.
  function select(mount: Mount, ctx: ToolContext): { module: ToolModule; index: number }[] {
    if (!MOUNTS.includes(mount)) throw new ToolIndexError(`unknown mount '${String(mount)}'`);
    if ((mount === 'investigator' || mount === 'investigator_deep') && ctx.entity === null) {
      throw new ToolIndexError(`mount ${mount} needs an entity in the tool context`);
    }
    const wanted: readonly Mount[] = mount === 'investigator_deep' ? ['investigator', 'investigator_deep'] : [mount];
    const picked: { module: ToolModule; index: number }[] = [];
    modules.forEach((module, index) => {
      if (!module.mounts.some((m) => wanted.includes(m))) return;
      if (module.entities !== 'all' && (ctx.entity === null || !module.entities.includes(ctx.entity))) return;
      picked.push({ module, index });
    });
    checkNames(mount, picked, sourceOf);
    return picked;
  }

  return Object.freeze({
    modules,
    allToolNames: () => [...new Set(modules.map((m) => m.name))].sort(),
    toolsFor(mount: Mount, ctx: ToolContext): ToolDefinition[] {
      const tools: ToolDefinition[] = [];
      for (const { module, index } of select(mount, ctx)) {
        if (!module.enabled(ctx, mount).on) continue;
        const tool = module.create(ctx, mount);
        if (tool.name !== module.name) {
          throw new ToolNameMismatchError(
            `${sourceOf(index)}: module '${module.name}' created a tool named '${String(tool.name)}'`,
          );
        }
        tools.push(tool);
      }
      return tools;
    },
    mountPlan(mount: Mount, ctx: ToolContext): readonly MountPlanRow[] {
      return select(mount, ctx).map(({ module }) => {
        const state = module.enabled(ctx, mount);
        return state.on ? { name: module.name, on: true } : { name: module.name, on: false, reason: state.reason };
      });
    },
  });
}

/**
 * Conformance rules every created tool must meet: an object input schema with
 * no entity or run id key (D3), and the module's name. Returns problems, empty
 * when the tool conforms.
 */
export function conformanceProblems(module: ToolModule, tool: ToolDefinition): string[] {
  const problems: string[] = [];
  if (tool.name !== module.name) problems.push(`created name '${tool.name}' differs from module name '${module.name}'`);
  const input = tool.input as { type?: unknown; entries?: Record<string, unknown> } | undefined;
  if (input === undefined || !OBJECT_SCHEMA_TYPES.has(String(input.type)) || input.entries === undefined) {
    problems.push('input schema is not a valibot object');
  } else {
    for (const key of FORBIDDEN_INPUT_KEYS) {
      if (Object.hasOwn(input.entries, key)) problems.push(`input schema has a '${key}' key`);
    }
  }
  return problems;
}

/** The contexts conformance runs a module under: each mount, and each entity it applies to there. */
export function conformanceCases(module: ToolModule): { mount: Mount; entity: Entity | null }[] {
  const cases: { mount: Mount; entity: Entity | null }[] = [];
  for (const mount of module.mounts) {
    const entityScoped = mount === 'investigator' || mount === 'investigator_deep';
    const entities: readonly (Entity | null)[] =
      module.entities === 'all' ? (entityScoped ? ENTITIES : [null]) : module.entities;
    for (const entity of entities) cases.push({ mount, entity });
  }
  return cases;
}

function checkModuleShape(m: ToolModule, source: string): void {
  if (typeof m?.name !== 'string') throw new ToolIndexError(`${source}: toolModule has no name`);
  if (!Array.isArray(m.mounts) || m.mounts.length === 0 || m.mounts.some((x) => !MOUNTS.includes(x))) {
    throw new ToolIndexError(`${source}: tool '${m.name}' mounts must be a non-empty list of ${MOUNTS.join(', ')}`);
  }
  const entitiesOk =
    m.entities === 'all' ||
    (Array.isArray(m.entities) && m.entities.length > 0 && m.entities.every((e) => ENTITIES.includes(e)));
  if (!entitiesOk) {
    throw new ToolIndexError(`${source}: tool '${m.name}' entities must be 'all' or a non-empty list of ${ENTITIES.join(', ')}`);
  }
  if (typeof m.enabled !== 'function' || typeof m.create !== 'function') {
    throw new ToolIndexError(`${source}: tool '${m.name}' needs enabled() and create()`);
  }
}

function checkNames(
  mount: Mount,
  picked: readonly { module: ToolModule; index: number }[],
  sourceOf: (index: number) => string,
): void {
  const seen = new Map<string, number>();
  for (const { module, index } of picked) {
    const name = module.name;
    if (!TOOL_NAME_PATTERN.test(name)) {
      throw new ToolIndexError(`${sourceOf(index)}: tool name '${name}' is not snake_case`);
    }
    if (RESERVED_TOOL_NAMES.includes(name)) {
      throw new ReservedToolNameError(`${sourceOf(index)}: tool name '${name}' is reserved by Flue`);
    }
    const other = seen.get(name);
    if (other !== undefined) {
      throw new DuplicateToolNameError(
        `duplicate tool name '${name}' on mount ${mount}: ${sourceOf(other)} and ${sourceOf(index)}`,
      );
    }
    seen.set(name, index);
  }
}

function sourceNamer(
  modules: readonly ToolModule[],
  sources: ToolIndexOptions['sources'],
): (index: number) => string {
  let list: readonly string[] | undefined;
  return (index) => {
    list ??= typeof sources === 'function' ? sources() : (sources ?? []);
    return list[index] ?? `tool module #${index} (${String(modules[index]?.name)})`;
  };
}

/**
 * Source files of the generated list, read from the import lines of
 * tool-modules.gen.ts. Only called when an error needs a file name. Returns
 * [] where the generated file is not on disk (a bundled build).
 */
export function generatedToolSources(): readonly string[] {
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    const text = readFileSync(join(here, 'tool-modules.gen.ts'), 'utf8');
    const found: string[] = [];
    for (const match of text.matchAll(/^import \{ toolModule as m(\d+) \} from '\.\/(.+)';$/gm)) {
      found[Number(match[1])] = `src/tools/${match[2]}`;
    }
    return found;
  } catch {
    return [];
  }
}

const defaultIndex = buildToolIndex(toolModules as readonly ToolModule[], { sources: generatedToolSources });

export const allToolModules: readonly ToolModule[] = defaultIndex.modules;
export const allToolNames = (): readonly string[] => defaultIndex.allToolNames();
export const toolsFor = (mount: Mount, ctx: ToolContext): ToolDefinition[] => defaultIndex.toolsFor(mount, ctx);
export const mountPlan = (mount: Mount, ctx: ToolContext): readonly MountPlanRow[] => defaultIndex.mountPlan(mount, ctx);
